# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de20fe2b7f7497e9d56713e414decd2a4c1fe45422ecc71115ec224dc587af8ef805b16f669f29b347ff828f693e06efdf1358301e08a84aab60e9f7bb53774a

test:
  secret_key_base: 43293d903cd8c7d21dd6d154a86b4fbc1089790abb64767f20a13fcf221047fda39c4a2ccd9edf4b70ffaa52449ee933d3ea99dd4d2dfb4f02d952c265a3eb25

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
